CREATE TABLE IF NOT EXISTS authors (
  id SERIAL PRIMARY KEY,
  email VARCHAR (100),
  password VARCHAR(255),
  name VARCHAR(120) NOT NULL,
  profile VARCHAR(120),
  role VARCHAR(20) DEFAULT 'user',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP DEFAULT NULL
);

CREATE INDEX if NOT EXISTS authors_id_idx ON authors(id);

CREATE TABLE IF NOT EXISTS blogs (
  id SERIAL PRIMARY KEY,
  author_id INTEGER REFERENCES authors(id) ON DELETE CASCADE,
  title VARCHAR(200) NOT NULL,
  description VARCHAR(400) NOT NULL,
  image VARCHAR(120),
  slug VARCHAR(200) NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP DEFAULT NULL
);

CREATE INDEX if NOT EXISTS blogs_slug_idx ON blogs(slug);
