CREATE TABLE IF NOT EXISTS authors (
  id SERIAL PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  profile VARCHAR(120) 
);

CREATE TABLE IF NOT EXISTS blogs (
  id SERIAL PRIMARY KEY,

  title VARCHAR(200) NOT NULL,
  description VARCHAR(400) NOT NULL,
  image VARCHAR(120),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
